[build]
  publish = "build"
  command = "npm run build && npm run sentry:sourcemaps"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Explicitly exclude directories
[build.processing.ignore]
  files = [
    "backend/**/*",
    "docs/**/*"
  ] 

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 