#!/bin/bash

echo "🎤 Testing Audio Flow"
echo "===================="
echo ""
echo "This script will help debug the audio flow from browser to backend."
echo ""
echo "1. Start the backend and watch for these logs:"
echo ""
echo "INITIAL CONNECTION:"
echo "  ✅ Groq service initialized"
echo "  🔌 New audio stream WebSocket connection"
echo "  📡 Audio stream connected for room: default, participant: user"
echo "  🔄 Connecting to Deepgram..."
echo "  ✅ Connected to Deepgram WebSocket"
echo ""
echo "AUDIO FLOW (when speaking):"
echo "  📤 PCM16 chunk #1 received for Deepgram, size: XXXX bytes"
echo "  🎵 Handling PCM16 audio data for Deepgram"
echo "  📊 Deepgram: Sent XX KB total"
echo "  📨 Deepgram message: { type: 'Results', hasTranscript: true, transcript: 'five' }"
echo ""
echo "  📹 WebM chunk #1 received for Groq, size: XXXX bytes"
echo "  📹 WebM audio data received for Groq"
echo "  🎯 Processing WebM chunk #1 with Groq"
echo "  ✅ Groq transcription completed in XXXms"
echo ""
echo "TRANSCRIPTION OUTPUT:"
echo "  📝 DEEPGRAM transcription: { originalText: 'five', sanitizedText: 'five', number: 5 }"
echo "  📝 GROQ transcription: { originalText: 'five', sanitizedText: 'five', number: 5 }"
echo "  🚀 Emitting transcription event"
echo ""
echo "2. In the browser console, you should see:"
echo "  🎬 Starting MediaRecorder recording..."
echo "  🛑 Stopping MediaRecorder recording..."
echo "  📦 MediaRecorder stopped, chunks collected: X"
echo "  🎵 WebM blob size: XXXXX bytes"
echo "  📤 Sending WebM data to backend: XXXXX bytes"
echo ""
echo "3. Common issues:"
echo "  - No PCM16 chunks = ScriptProcessor not working"
echo "  - No WebM chunks = MediaRecorder not working"
echo "  - No Deepgram messages = Deepgram WebSocket issue"
echo "  - No Groq results = Groq API or format issue"
echo ""
echo "Press Ctrl+C to exit"